# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build
on: [ push, pull_request ]
jobs:
    build:
        strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                java: [
                    17,    # Current Java LTS & minimum supported by Minecraft
                ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v2
            -   uses: gradle/wrapper-validation-action@v1
            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   name: Grant execute permission for gradlew
                if: ${{ runner.os != 'Windows' }}
                run: chmod +x gradlew
            -   name: Build with Gradle
                run: ./gradlew build --stacktrace
            -   name: Capture build artifacts
                if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from the latest java on one OS
                uses: actions/upload-artifact@v2
                with:
                    name: Artifacts
                    path: |
                        common/build/libs/
                        fabric/build/libs/
                        forge/build/libs/
